---
deployment:
tasks:
- export DEPLOYPATH=/home/elirorealty/public_html/
- /bin/cp -u index.html $DEPLOYPATH
- /bin/cp -u main.css $DEPLOYPATH
- /bin/cp -u robots.txt $DEPLOYPATH
- /bin/cp -R fonts $DEPLOYPATH
- /bin/cp -R images $DEPLOYPATH

 
