---
deployment:
tasks:
 - export DEPLOYPATH=/home/elirorealty/public_html/
 - /bin/cp -R index.html $DEPLOYPATH
 - /bin/cp -R main.css $DEPLOYPATH
 - /bin/cp -R robots.txt $DEPLOYPATH
 - /bin/cp -R fonts $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH

 
